name: Publish Package

on:
  # release:
  #   types: [created]
  push:
    branches:
      - master

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x
  #     - run: yarn install --frozen-lockfile
  #     - run: yarn test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: "@pulsarml"
      - run: yarn install --frozen-lockfile
      - run: echo registry=https://npm.pkg.github.com/pulsarml >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
